### PR TITLE
Fix namespace for DateTime

### PR DESCRIPTION
**Pull request by derweba**
Fixes #22

### CODE REVIEW

**Comment by Benjamin-K** [comment]
Thanks for the fix. Could I kindly ask you to do one more improvement here, as we have more data stored in the database? 

Could you please replace
```php
new \DateTime($value['date'])
```
with
```php
\DateTime::createFromFormat($value['dateFormat'], $value['date'], $value['timezone'])
```

Thank you! :)

**Comment by derweba** [comment]
Sure! Great suggestion.

**Comment by derweba** [comment]
Implemented your suggested improvement.

**Comment by Benjamin-K** [comment]
Thy, I already created a new release.

**Pull request merged**
